### ISSUE TITLE
Missing from packagist?

### ISSUE THREAD

**Issue by mallardduck** [RobThree/HumanoID#1]
Hey @RobThree - Is this package still something you'd like to maintain?

I haven't tried it yet, but it seems useful for a use-case I have. However when I tried to pull it in I noticed it's missing from packagist. Not sure if this was intentional or an oversight so figured I should ask. If you don't wish to publish and maintain it I may fork it and do so myself. Or I'd be happy to throw PRs your way to address getting it ready for packagist.

If you would like some help preparing and shipping a release I'd also _highly_ suggest giving a real consideration to renaming it. Many frameworks have "UrlGenerator" features that do vastly different things than this package. I think taking inspiration from a similar library on NPM (TS) called `zoo-ids` might be a good fit.

**Comment by RobThree** [comment]
Hey, 

That's an incredible coincidence. Just earlier this week I came across this repo (I was cleaning up a few older ones) and thought to myself: this could use some attention.

If you'd like to provide a PR to make it ready for packagist, that would be much appreciated. As for the name: suggestions are welcome.

I'd be happy to publish it and maintain it as much and as long as possible.

**Comment by mallardduck** [comment]
Awesome, I've already got a fork made (which I renamed to ZooIdGenerator, we can land on a name before I send a PR here) where I'll get working.

One reason I'd prefer to exclude URL from the main name, but prefer including in descriptions, is that this could be used in contexts other than URLs. While URLs maybe the most common I do think that framing it in that way undersells how useful and general purpose this could be.

For instance, using a library like this you could generate human friendly unique identifiers for IRL objects. Consider a business that may have alphanumerical IDs on equipment, they could also include an Adjective (scoped to colors) and Animal based visual ID.

One odd thing I've run into is that the tests are failing even before I've changed anything functional. So this makes me curious about the "backend" mechanics in use here and if those are affected by changes to arrays across major PHP versions. Ensuring that the supported versions produce consistent results across major versions will be important.

**Comment by RobThree** [comment]
> One reason I'd prefer to exclude URL from the main name, but prefer including in descriptions, is that this could be used in contexts other than URLs. While URLs maybe the most common I do think that framing it in that way undersells how useful and general purpose this could be.

That is a very good point. I agree, let's get rid of URL in the name.

> One odd thing I've run into is that the tests are failing

I'll have to look into that. Which test is failing on what?

> Ensuring that the supported versions produce consistent results across major versions will be important.

Absolutely agree.

**Comment by mallardduck** [comment]
https://github.com/RobThree/UrlGenerator/blob/44cf4071f074b4f2fc4d595be016ecfe004b2d59/tests/UrlGeneratorTests.php#L20

```
--- Expected
+++ Actual
@@ @@
-'red-dog'
+'green-dog'
```

Based on this being created 3 years ago I was wondering if you initially created it on PHP 5.6 (or maybe at newest 7.0)?

It's possible some of the PHP engine changes that happened between 5.x and 7.x caused this test break. This seems likely as when I switched from 8.1 to 7.4 I see the same issues. Though it's possible that a 7.x minor release caused the change, so maybe I should try 7.0 as well.

In any case as I have time thru my workday today I'll keep poking around at it to see how things are sitting. If this project was started on PHP 5.6 I may even just see if I can get that version installed via homebrew and then start from t here.

**Comment by RobThree** [comment]
No it has nothing to do with PHP versions or anything; I was (back then) trying to implement a specific behavior and that's what the unittest was for; it was supposed to "go green" once I had achieved my goal. But I later concluded that the behavior as it is right now is correct. So the unittest can just be trashed.

I'm not sure on which version I wrote it, I guess 7.0. I'm just trying to get the thing back up and running here to. Give me a few minutes and I'll push my changes/fixes.

**Comment by RobThree** [comment]
I removed the test and fixed the composer.json file. It's been a long time since I wrote this code so I'm a bit rusty 😬

**Comment by mallardduck** [comment]
Sick, I'll pull in the changes and start a branch to write some tests and do some house keeping and such. 😄

**Comment by mallardduck** [comment]
> though "zoo-ids" (though a nice name) imply a bit too much that it's (or has to be) animal related so I'd like a bit more generic name

This is a great point - as while Animals could be one set of nouns someone uses they could certainly pick any other set too. I'll do some thinking on this part as well to come up with a few suggestions.

**Comment by RobThree** [comment]
I've merged #2 and updated the project name and README. Added @MueR to the composer file and added a logo. Are we ready to ship? 😉 Am I forgetting something?

**Comment by mallardduck** [comment]
Looking all good from my PoV. I'd say ship it 🚀 .

Can always sort out adding the tags to composer.json and github later. :)

**Comment by RobThree** [comment]
If I'm not mistaken then we're "live". Good work people!

![top-gun-high-five-580-100538112-orig](https://user-images.githubusercontent.com/607888/164315532-aa817098-9b48-43b1-b63b-8004613aedb4.gif)

**Comment by RobThree** [comment]
Crap 🤦‍♂️
Immediately after I publish I remembered what I forgot. I wanted to randomize the wordlist (`space-words.json`); the words there are in alphabetical order and I prefer them in random order since it makes the HumanoIDs a little less 'predictable'. But no biggy whatsoever. As far as I'm concerned people should provide their own word lists anyway.

**Comment by mallardduck** [comment]
Ohh - that's a good point. I suppose we could always:
1. Commit to randomize our word files,
2. Force delete the version tag,
3. Delete the release from packagist,
4. Retag the release on top of the new commit.

**Comment by RobThree** [comment]
Meh, we could also accept that they're in alphabetical order. Hell, if anything, it kind of drives the point home that HumanoID's are predictable and only a very light way of 'obscuring' integer ID's. Either way is fine with me, but I'm OK with it as it currently is.

**Comment by mallardduck** [comment]
I'm sold on that. 😄 One default wordset is alphabetical and more predictable, the other default is randomized and less predictable. We can just document that as a feature even!

**Comment by RobThree** [comment]
> We can just document that as a feature even!

Exactly.

On another note: I am REALLY happy with the name, I like it more and more. It made the README a lot more fun to read too. I think I'll add the (intended) pronunciation to the README, but only at the very bottom so that only THEN people will discover it's pronounced Humano-I-D 😂
