### ISSUE TITLE
Adding more variety / "randomness"

### ISSUE THREAD

**Issue by teamcoltra** [RobThree/HumanoID#15]
I haven't looked at the code to be honest and my math and big brain skills are lacking but it seems like the current system goes down the last word list then second last sequentially so you can tell the similar IDs because they will be 

Gold-monkey
Gold-zebra
Gold-pig

Etc

Would it be computationally difficult or difficult to add a way of parsing through the list in order for each item so red-monkey, blue-zebra,pink-pig etc

**Comment by RobThree** [comment]
See #5 and #13 
Yes, it's possible 😉
