### ISSUE TITLE
Docs Improvement: Add installation command and namespace to readme

### ISSUE THREAD

**Issue by caendesilva** [RobThree/HumanoID#7]
I have to feature requests for the readme:

Add the composer installation command for easy copy and paste
```bash
composer require robthree/humanoid
```

Add the proper namespace in the example, had to look at the source to see that I needed the following:
```php
use RobThree\HumanoID\HumanoIDs;
```

Edit: While looking at the source I found the spaceIdGenerator which I think is cooler. Something to add to the readme as well?

**Comment by RobThree** [comment]
BAM!
